CREATE TABLE `reservation_section` (
    `ID` INT(11) AUTO_INCREMENT NOT NULL,
    `NAME` VARCHAR(256) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE `reservation_hall` (
    `ID` INT(11) AUTO_INCREMENT NOT NULL,
    `NAME` VARCHAR(256) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE `reservation_scheme` (
    `ID` INT(11) AUTO_INCREMENT NOT NULL,
    `ID_HALL` INT(11) NOT NULL,
    `ID_SECTION` INT(11) NOT NULL,
    `ID_ROW` INT(11) NOT NULL,
    `ID_COLUMN` INT(11) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (ID_HALL) REFERENCES reservation_hall(ID),
    FOREIGN KEY (ID_SECTION) REFERENCES reservation_section(ID)
);

CREATE TABLE `reservation_seance` (
    `ID` INT(11) AUTO_INCREMENT NOT NULL,
    `ID_HALL` INT(11) NOT NULL,
    `ID_FILM` INT(11) NOT NULL,
    `START_TIME` TIMESTAMP NOT NULL,
    `SECTION_PRICES` VARCHAR(256) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (ID_HALL) REFERENCES reservation_hall(ID)
);

CREATE TABLE `reservation_ticket` (
    `ID` INT(11) AUTO_INCREMENT NOT NULL,
    `ID_USER` INT(11) NOT NULL,
    `ID_SEANCE` INT(11) NOT NULL,
    `ID_HALL` INT(11) NOT NULL,
    `ID_ROW` INT(11) NOT NULL,
    `ID_COLUMN` INT(11) NOT NULL,
    `PRICE` INT(11) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (ID_SEANCE) REFERENCES reservation_seance(ID),
    FOREIGN KEY (ID_HALL) REFERENCES reservation_hall(ID)
);